### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by muza402** [minoruta/ast_mongo#5]
I have an established asterisk. How can I add your module?

**Comment by minoruta** [comment]
@muza402

I see, you need binary.

Here's just my idea;
1. build pulugins on another linux with same version of your asterisk,
1. copy plugins from it to your system,
1. copy the related libs to your system as well.

The essential binaries will be;

```
# cd /
# tar czf ast_mongo.binaries.tgz \
    /usr/lib/asterisk/modules/res_mongodb.so \
    /usr/lib/asterisk/modules/res_config_mongodb.so \
    /usr/lib/asterisk/modules/cdr_mongodb.so \
    /usr/lib/asterisk/modules/cel_mongodb.so \
    /usr/local/lib/libmongoc* \
    /usr/local/lib/libbson* 
```

**Comment by muza402** [comment]
Modules are not available during compilation. Is it connected with anything?
![image](https://cloud.githubusercontent.com/assets/28109826/25516483/4c34e68e-2c04-11e7-9dc7-69996283bff4.png)

**Comment by minoruta** [comment]
@muza402

In order to build your custom plugins,
there are following two ways for instance;
1. build them with [ast_mongo test bench](https://github.com/minoruta/ast_mongo/tree/master/asterisk/test_bench),
1. write your own shell script to build them based on [my script](https://github.com/minoruta/ast_mongo/blob/master/asterisk/test_bench/scripts/provisioning.sh).

In your case, you  might have failed to detect essential library such as libmongoc while your `./configure` process.

**Comment by minoruta** [comment]
Any update or I'll close this issue.

Thanks

**Comment by minoruta** [comment]
I close this issue,
thanks.

**Comment by malarinv** [comment]
Any plan to upstream this awesome plugin to asterisk?

**Comment by minoruta** [comment]
@malarinv 
No, not at all. Thanks.
